[book]
authors = ["SnackS"]
language = "en"
multilingual = false
src = "src"
title = "Dayz Tutorials"

[build]
extra-watch-dirs = ["po", "listings"]
create-missing = false

[preprocessor.gettext]
after = ["links"]

[output.html]
git-repository-url = "https://github.com/SnackSBR/dayz-tutorial"
additional-css = [
	"theme/language-picker.css",
]
additional-js = [
	"theme/language-picker.js",
]